### ISSUE TITLE
[Linux] Overlay scrollbar obscures "pinned" icon

### ISSUE THREAD

**Issue by ptziegler** [eclipse-gef/gef-classic#569]
I wonder if it makes sense to disable the overlay scrollbar by default...

![image](https://github.com/user-attachments/assets/12a0be04-00b9-42d1-bca9-70e4f644322d)

**Comment by azoitl** [comment]
Would make sense for me. Even if would break a bit the look and feel of the target platform. But overlay scrollbars are anyhow an usability nightmare.
